runtime: nodejs10

instance_class: F2

handlers:
  - url: /_nuxt
    static_dir: app/.nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: app/static/\1
    upload: app/static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

# env_variables:
#   HOST: '0.0.0.0'
#   NODE_ENV: 'production'

