steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions/'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'functions', 'deploy', 'order', '--runtime nodejs8','--trigger-http']
  dir: 'functions/'